<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [2]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.21.2
Pandas:  1.3.4


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [ ]:
# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('data/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?ANSWER: The main thing wrong with these 3 calls is that there's no seperator/delimiter included in the arguments. To correctly load the file a sep=',' should be included.
To correctly load the column names the header should be set as header=0 as they are not passed explecitedly.

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [74]:
#ANSWER:
bikes = pd.read_table('data/bikeshare.csv', sep=',', index_col=0)
bikes.head()

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
1        2011-01-01       1   0     1   0        0        6           0   
2        2011-01-01       1   0     1   1        0        6           0   
3        2011-01-01       1   0     1   2        0        6           0   
4        2011-01-01       1   0     1   3        0        6           0   
5        2011-01-01       1   0     1   4        0        6           0   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
1                 1  0.24  0.2879  0.81        0.0       3          13   16  
2                 1  0.22  0.2727  0.80        0.0       8          32   40  
3                 1  0.22  0.2727  0.80        0.0       5          27   32  
4                 1  0.24  0.2879  0.75        0.0       3          10   13  
5                 1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [5]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [6]:
df = pd.read_excel('Data/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [7]:
#ANSWER
df = pd.read_excel('Data/Iris.xls', header=0, usecols=[1,2,3,4,5], index_col=4)
df

Petal_width  Petal_length  Sepal_width  Sepal_length
Species_name                                                      
 Setosa               0.2           1.4          3.5           5.1
 Setosa               0.2           1.4          3.0           4.9
 Setosa               0.2           1.3          3.2           4.7
 Setosa               0.2           1.5          3.1           4.6
 Setosa               0.2           1.4          3.6           5.0
...                   ...           ...          ...           ...
 Verginica            2.3           5.2          3.0           6.7
 Verginica            1.9           5.0          2.5           6.3
 Verginica            2.0           5.2          3.0           6.5
 Verginica            2.3           5.4          3.4           6.2
 Verginica            1.8           5.1          3.0           5.9

[150 rows x 4 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [8]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [9]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

# Load 
df = pd.read_html(url)[0]
df

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

In [11]:
url = 'http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/'

# Load the XML file into a dataframe
df = pd.read_html(url)[0]
df.head()

Unnamed: 0        ID                                             String  \
0           0  id_a_f_3              !Susie (http://www.sync2it.com/susie)   
1           1  id_a_f_6  <a href='http://www.unchaos.com/'> UnChaos </a...   
2           2  id_a_f_7  <a href='http://www.unchaos.com/'> UnChaos Bot...   

                                       Description Type       Comment  \
0  Sync2It bookmark management & clustering engine  C R          None   
1                             UnCHAOS search robot    R  Site is dead   
2                             UnCHAOS search robot    R  Site is dead   

                     Link1 Link2  
0   http://www.sync2it.com  None  
1  http://www.unchaos.com/  None  
2  http://www.unchaos.com/  None

#### Importing JSON Files from the Web
https://www.dataquest.io/blog/python-json-tutorial/

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [12]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [13]:
#ANSWER
bikes.shape

(17379, 16)

What are the column names in `bikes`?

In [14]:
#ANSWER
bikes.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [15]:
#ANSWER
bikes.dtypes

dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [16]:
#ANSWER
bikes.index

Int64Index([    1,     2,     3,     4,     5,     6,     7,     8,     9,
               10,
            ...
            17370, 17371, 17372, 17373, 17374, 17375, 17376, 17377, 17378,
            17379],
           dtype='int64', name='instant', length=17379)

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [17]:
#ANSWER
print(type(bikes['season']))
print(type(bikes[['season']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


How would we use object notation to show the first 4 rows of `atemp`?

In [18]:
#ANSWER
#N.B: Call atemp as an object, don't use .head()
bikes.atemp[:4]

instant
1    0.2879
2    0.2727
3    0.2727
4    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [63]:
#bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [19]:
#ANSWER
bikes.iloc[0]

dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed            0.0
casual                 3
registered            13
cnt                   16
Name: 1, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [20]:
#ANSWER
bikes.iloc[:,1]

instant
1        1
2        1
3        1
4        1
5        1
        ..
17375    1
17376    1
17377    1
17378    1
17379    1
Name: season, Length: 17379, dtype: int64

## Handling Missing Values

What is the Pandas `isnull` function for? 

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [21]:
bikes.isnull().head()

dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
instant                                                                      
1         False   False  False  False  False    False    False       False   
2         False   False  False  False  False    False    False       False   
3         False   False  False  False  False    False    False       False   
4         False   False  False  False  False    False    False       False   
5         False   False  False  False  False    False    False       False   

         weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
instant                                                                         
1             False  False  False  False      False   False       False  False  
2             False  False  False  False      False   False       False  False  
3             False  False  False  False      False   False       False  False  
4             False  False  False  False      False   False       False  False  
5             False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [22]:
#ANSWER
bikes.isnull().sum().sum()


0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [23]:
#ANSWER
bikes.isnull().sum()

dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

Write (and verify) a function that performs simple division with built-in handling of the edge case (i.e. return a nan value instead of just producing an error):

In [28]:
#ANSWER
def div(n,d):
    if n == 0 or d == 0:
        return np.nan
    else:
        return n/d
        
div(1,0)

nan

Apply the Pandas `isna` function to the following data objects:

In [30]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [31]:
#ANSWER
pd.isna(x)
pd.isna(y)

True

In [32]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [33]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [34]:
#ANSWER
bikes[['season']].value_counts()

season
3         4496
2         4409
1         4242
4         4232
dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [35]:
#ANSWER
def ran(column):
    print(f'The {column.name} column has a minum of {column.min()} and a maximum of {column.max()}')
    return

ran(bikes.index)
ran(bikes.dteday)
ran(bikes.windspeed)


The instant column has a minum of 1 and a maximum of 17379
The dteday column has a minum of 2011-01-01 and a maximum of 2012-12-31
The windspeed column has a minum of 0.0 and a maximum of 0.8507


Compute and print the overall minimum and maximum of the data columns:

In [36]:
#ANSWER
print(bikes.min())
print(bikes.max())

dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                0
workingday             0
weathersit             1
temp                0.02
atemp                0.0
hum                  0.0
windspeed            0.0
casual                 0
registered             0
cnt                    1
dtype: object
dteday        2012-12-31
season                 4
yr                     1
mnth                  12
hr                    23
holiday                1
weekday                6
workingday             1
weathersit             4
temp                 1.0
atemp                1.0
hum                  1.0
windspeed         0.8507
casual               367
registered           886
cnt                  977
dtype: object


### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [37]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [38]:
#ANSWER
quant = (0.1, 0.25, 0.5, 0.75, 0.9)

bikes.atemp.quantile(quant)

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [39]:
type(bikes['atemp'])

pandas.core.series.Series

In [40]:
bikes.sample(5)

dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
instant                                                                   
10544    2012-03-20       1   1     3  10        0        2           1   
420      2011-01-19       1   0     1  12        0        3           1   
10549    2012-03-20       1   1     3  15        0        2           1   
12845    2012-06-24       3   1     6   9        0        0           0   
14274    2012-08-22       3   1     8  22        0        3           1   

         weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
instant                                                                      
10544             1  0.54  0.5152  0.88     0.1940      44         119  163  
420               2  0.30  0.3182  0.81     0.0896       5          65   70  
10549             2  0.62  0.6061  0.69     0.1045      67         177  244  
12845             1  0.72  0.6667  0.51     0.0000      63         169  232  
14274             1  0.64  0.6061  0.73     0.0000      55         226  281

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [41]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [42]:
#ANSWER
type(atemp_level)

pandas.core.series.Series

Here is a random sample of `atemp_level`:

In [43]:
atemp_level.sample(5)          

instant
10607    (0.5, 0.75]
5475     (0.5, 0.75]
4068     (0.5, 0.75]
11943    (0.5, 0.75]
9250     (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64, right]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [44]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)

instant
16216    mild
14144    cool
17250    cool
12560    warm
3123     mild
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [46]:
#ANSWER
bikes['atemp_level'] = atemp_level
print(f"Numbers of mild temp in season 2 = {bikes.atemp_level[(bikes.season == 2)].value_counts()['mild']}")

Numbers of mild temp in season 2 = 1829


*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [48]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [49]:
# Cleaning Data
print(a.shape,' ',a,'\n',
b.shape,' ',b,'\n',
c.shape,' ',c,'\n',
d.shape,' ',d,'\n',
e.shape,' ',e)


(3,)   [0. 0. 0.] 
 (1, 3)   [[1. 1. 1.]] 
 (2, 3, 4)   [[[7 4 1 9]
  [6 5 8 3]
  [5 4 4 6]]

 [[2 4 3 5]
  [4 2 1 8]
  [6 1 2 2]]] 
 (4,)   [0 1 2 3] 
 (2, 4)   [[1 2 3 4]
 [5 6 7 8]]


## Load Data

Load rock.csv and clean the dataset.

In [88]:
#ANSWER
#Load csv into a pandas DataFrame
df = pd.read_csv('Data/rock.csv')
#Check DF head
df.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [51]:
#ANSWER
#Check column names
df.columns
#change all column names to lower case and clean
df.columns = df.columns.str.lower().str.replace('?','').str.replace('*','').str.replace(' ','_')
#check resulting DF
df.head()

/var/folders/wh/5l_c08654yvfc0h71fmq8pxr0000gn/T/ipykernel_6057/3151328314.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.columns = df.columns.str.lower().str.replace('?','').str.replace('*','').str.replace(' ','_')


song_clean artist_clean release_year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                combined  first  year  playcount  fg  
0        Caught Up in You by .38 Special      1     1         82  82  
1            Fantasy Girl by .38 Special      1     0          3   0  
2         Hold On Loosely by .38 Special      1     1         85  85  
3  Rockin' Into the Night by .38 Special      1     1         18  18  
4              Art For Arts Sake by 10cc      1     1          1   1

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [52]:
#ANSWER
#check if there's any null values in release_year
df.release_year.isnull().sum()
#replace null values with 0
df.release_year.fillna(value=0, inplace=True)

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [53]:
#ANSWER
#check data types
df.dtypes
#change release year to int32
#df.release_year = df.release_year.astype('int')
#replace SONGFACTS.COM from release_year
df.replace(to_replace='SONGFACTS.COM',value=0,inplace=True)
#Change release_year to int
df.release_year = df.release_year.astype('int64')
#check data types
df.dtypes

song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [54]:
#ANSWER
df.dtypes


song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [55]:
#ANSWER
def sar(row):
    print(f'Song: {row["song_clean"]}')
    print(f'Artist: {row["artist_clean"]}')
    if row['release_year'] < 1970:
        print('Release year is prior to 1970')
    else:
        print('Release year is 1970 or later')
        
    return

sar(df.iloc[1])

Song: Fantasy Girl
Artist: .38 Special
Release year is prior to 1970


## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [119]:
#ANSWER
def to_float(df):
    for i in df:
        if df[i].dtypes != 'int64':
            df[i] = np.NaN
        else:
            df[i] = df[i].astype('int64')
    return df

## Apply these functions to your dataset

In [120]:
#ANSWER
to_float(df)

Song Clean  ARTIST CLEAN  Release Year  COMBINED  First?  Year?  \
0            NaN           NaN           NaN       NaN       1      1   
1            NaN           NaN           NaN       NaN       1      0   
2            NaN           NaN           NaN       NaN       1      1   
3            NaN           NaN           NaN       NaN       1      1   
4            NaN           NaN           NaN       NaN       1      1   
...          ...           ...           ...       ...     ...    ...   
2225         NaN           NaN           NaN       NaN       1      0   
2226         NaN           NaN           NaN       NaN       1      1   
2227         NaN           NaN           NaN       NaN       1      1   
2228         NaN           NaN           NaN       NaN       1      1   
2229         NaN           NaN           NaN       NaN       1      1   

      PlayCount  F*G  
0            82   82  
1             3    0  
2            85   85  
3            18   18  
4             1    1  
...         ...  ...  
2225          1    0  
2226         32   32  
2227        109  109  
2228          1    1  
2229          2    2  

[2230 rows x 8 columns]

## Describe the new float-only DataFrame.

In [121]:
#ANSWER
df.describe()

Song Clean  ARTIST CLEAN  Release Year  COMBINED  First?        Year?  \
count         0.0           0.0           0.0       0.0  2230.0  2230.000000   
mean          NaN           NaN           NaN       NaN     1.0     0.741256   
std           NaN           NaN           NaN       NaN     0.0     0.438043   
min           NaN           NaN           NaN       NaN     1.0     0.000000   
25%           NaN           NaN           NaN       NaN     1.0     0.000000   
50%           NaN           NaN           NaN       NaN     1.0     1.000000   
75%           NaN           NaN           NaN       NaN     1.0     1.000000   
max           NaN           NaN           NaN       NaN     1.0     1.000000   

         PlayCount          F*G  
count  2230.000000  2230.000000  
mean     16.872646    15.048430  
std      25.302972    25.288366  
min       0.000000     0.000000  
25%       1.000000     0.000000  
50%       4.000000     3.000000  
75%      21.000000    18.000000  
max     142.000000   142.000000



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



